config/routes.rb
Rails.application.routes.draw do
   devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :courses
  resources :homes
  resources :groups
  get '/csv' => 'homes#csv' 
  root 'starts#index'
  post '/search' => 'searchs#show'

end

app/models/college.rb
class College < ActiveRecord::Base
	has_many :departments
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :lnventories
        has_many :locations
        has_many :groups
	has_one :syllabus
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :courses
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
end

app/models/lnventory.rb
class Lnventory < ActiveRecord::Base
	belongs_to :course
	belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
end

app/models/syllabus.rb
class Syllabus < ActiveRecord::Base
	belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,:omniauthable, :omniauth_providers => [:facebook]
  has_many :lnventories
  belongs_to :homes
 # belongs_to :groups

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end 
end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
	end
	def show
		@department = Department.find(params[:id])
		@courses = Course.where("department_id = ?",params[:id])	
	end
	def create
		@course = Lnventory.where(:user_id => current_user.id , :course_id => params[:course_id]).first_or_create
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
	end
	def show
		@course = Course.find(params[:id])
		@group = @course.groups.new
		course_id = @course.course_id.to_s.rjust(4,'0')
		term = @course.year.to_s.last
		year = @course.year.to_s[0..2]
		@uri = "http://140.128.97.216/102/teac2_desc/outline4/print_outline.php?setyear=#{year}&setterm=#{term}&curr_code=#{course_id}&ss_sysid=otr"
		@groups = @course.groups
		if @groups.count > 0
		@group_num = (@course.groups.average(:num_1) + @course.groups.average(:num_2))/2
		@group_num1 = @course.groups.average(:num_1)
		@group_num2 = @course.groups.average(:num_2)
		end
	end
 	def create
    		@course = Course.find(params[:course_id])
    		@group = @course.groups.build(post_params)
    		@group.user_id = current_user.id
    		@group.save
		if @group.save
		     redirect_to group_path(@course), notice: "新增評論成功"
		end
	end
private
def post_params
     params.require(:group).permit(:num_1,:num_2,:num_3, :comment)
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
 # before_action :set_home, only: [:show, :edit, :update, :destroy]
  require 'csv' 
  def index
	@user = User.find(current_user.id)
	@lnventory = @user.lnventories
	i=0
	r=[]
	@lnventory.each do |ln|
		r[i] = ln.course_id
		i+=1
	end	
	@recommend = Recommendation.where(recommend_id: r).order("times DESC").limit(10)
  end

  def edit
	@user = User.find(current_user.id)
	@lnventory = @user.lnventories
  end

  def destroy
	@lnventory = Lnventory.where("user_id = %s AND course_id = %s ", current_user.id , params[:course_id])
	@lnventory[0].destroy
  end 

  def csv
	head = 'EF BB BF'.split(' ').map{|a|a.hex.chr}.join()
        csv_string = CSV.generate(csv=head) do |csv|

	title=['日期時間','星期一      ','星期二      ','星期三       ','星期四      ','星期五      ','星期六      ']
	csv << title
	arr=[];
	@lnventory = User.find(current_user.id).lnventories
		(1..14).each do |y|
        		if y==5 
                		arr.push('b')
        		elsif y>5
				k=y-1
				k=k.to_s
                		arr.push(k)
        		else
               			k=y.to_s
				arr.push(k)
			end
        			
        	(1..6).each do |x|
                	chack=(y-1)*6+x
			body=""
                 	@lnventory.each do |t| 
                         	t.course.locations.each do |k| 
                                 	if k.time == chack 
						body=body+
                                         	t.course.course_id.to_s.rjust(4,'0')+"\n"+
                                         	t.course.name + "\n" +
                                         	t.course.date+"\n" +
                                         	t.course.teacher
                                	 end 

                       		 end 
			end 
				arr.push(body)
		end 
			csv<<arr
			arr.clear
	end 
        end
        csv_string.force_encoding('utf-8')
        send_data csv_string, :filename => current_user.name+"的課表.csv"

  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
	def show
		@courses = Course.where("`course_id` = ?  or `name` LIKE ?  or `teacher` LIKE ? ",params[:q],"%#{params[:q]}%","%#{params[:q]}%")
	end
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def notice_message
   alert_types = { notice: :success, alert: :danger }

   close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
   close_button = content_tag(:button, "×", close_button_options)

   alerts = flash.map do |type, message|
     alert_content = close_button + message
     alert_type = alert_types[type.to_sym] || type
     alert_class = "alert alert-#{alert_type} alert-dismissable"

     content_tag(:div, alert_content, class: alert_class)
   end

   alerts.join("\n").html_safe
 end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/starts_helper.rb
module StartsHelper
end

app/views/common/_courseside.html.erb
    <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
<% if current_user %>
      <div class="user-panel">
        <div class="pull-left image">
	<%= image_tag(current_user.image+"?type=square", :class => "img-circle")%>
        </div>
        <div class="pull-left info">
          <p><%=current_user.name%></p>
          <!-- Status -->
          <a href="#"><i class="fa fa-fw fa-calendar-check-o"></i><%=Time.now.strftime("%Y-%m-%d")%></a>
        </div>
      </div>
<%end%>
      <!-- search form (Optional) -->
	<%=form_tag "/search" ,:class => 'sidebar-form'  do %>
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="輸入想搜尋的課程">
              <span class="input-group-btn">
                <button type="submit" name="btn" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      <%end%>
      <!-- /.search form -->

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
<% if current_user %>
       <li class="header">功能</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="treeview">
          <a href="/homes"><i class="fa fa-link"></i> <span>我的課表</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li><%=link_to "我的課表", homes_path%></li>
            <li><%=link_to "編輯課表", edit_home_path("#")%></li>
            <li><%=link_to "推薦課程", "#"%></li>
            <li><%=link_to "輸出excel", csv_path%></li>
          </ul>
        </li>
<%end%>
        <li class="header">學校課程</li>
        <!-- Optionally, you can add icons to the links -->
	<%College.all.each do |college|%>
        <li class="treeview">
          <a href="">
		<i class="fa fa-book"></i>
			<span><%=college.name%></span>
		<i class="fa fa-angle-left pull-right"></i>
	  </a>
          <ul class="treeview-menu">
	    <%college.departments.each do |department|%>
            <li><%= link_to department.name , course_path(department)%> </li>
	    <%end%>
          </ul>
        </li>
	<%end%>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

app/views/common/_footer.html.erb
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Herbert</a>.</strong> All rights reserved.
</footer>

app/views/common/_navbar.html.erb
  <header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>U</b>NI</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Uni</b>Note</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
      </div>
    </nav>
  </header>

app/views/common/_userside.html.erb
    <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
	<%= link_to image_tag(current_user.image+"?type=square", :class => "img-circle"), "http://facebook.com/#{current_user.uid}"%>
        </div>
        <div class="pull-left info">
          <p><%=current_user.name%></p>
          <!-- Status -->
          <a href="#"><i class="fa fa-fw fa-calendar-check-o"></i><%=Time.now.strftime("%Y-%m-%d")%></a>
        </div>
      </div>


      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header">MENU</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>我的課表</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li><a href="#">開始選課</a></li>
            <li><a href="#">編輯課表</a></li>
            <li><a href="#">課程推薦</a></li>
            <li><a href="#">輸出excel</a></li>
          </ul>
        </li>
        <li class="active"><a href="#"><i class="fa fa-link"></i> <span>a</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

app/views/layouts/application.html.erb
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <title>UNINOTE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body class="hold-transition skin-blue-light sidebar-mini">
<div class="wrapper">
<%= render "common/navbar" %>  
<%= render "common/courseside" %>   
  <div class="content-wrapper">
<%= notice_message %>
        <%= yield %>
  </div>

<%= render "common/footer" %>   

</div>
<script>
	$.AdminLTE.tree('.sidebar');
</script>
</body>
</html>